// <auto-generated />
using System;
using LocalChat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalChat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319221250_AddGenerationPromptSnapshots")]
    partial class AddGenerationPromptSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LocalChat.Domain.Entities.Audio.SpeechClip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativeUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Voice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MessageId");

                    b.ToTable("SpeechClips", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultGenerationPresetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultModelProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTtsVoice")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultVisualNegativePrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultVisualPromptPrefix")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultVisualStylePreset")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Greeting")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalityDefinition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultGenerationPresetId");

                    b.HasIndex("DefaultModelProfileId");

                    b.HasIndex("Name");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Characters.CharacterSampleDialogue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssistantMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "SortOrder")
                        .IsUnique();

                    b.ToTable("CharacterSampleDialogues", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BranchedFromMessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorInstructions")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DirectorInstructionsUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOocModeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RuntimeGenerationPresetOverrideId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RuntimeModelProfileOverrideId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneContext")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SceneContextUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserPersonaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchedFromMessageId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ParentConversationId");

                    b.HasIndex("RuntimeGenerationPresetOverrideId");

                    b.HasIndex("RuntimeModelProfileOverrideId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserPersonaId");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Conversations.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedVariantIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Conversations.MessageVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GenerationCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GenerationPresetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GenerationStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModelProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProviderType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RuntimeSourceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VariantIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("ModelIdentifier");

                    b.HasIndex("ProviderType");

                    b.HasIndex("MessageId", "VariantIndex")
                        .IsUnique();

                    b.ToTable("MessageVariants", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Conversations.SummaryCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReplacedByCheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "EndSequenceNumber");

                    b.ToTable("SummaryCheckpoints", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Generation.GenerationPromptSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedPromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GenerationPresetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageVariantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModelProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptSectionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProviderType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResolvedContextWindow")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RuntimeSourceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MessageId");

                    b.HasIndex("MessageVariantId")
                        .IsUnique();

                    b.HasIndex("ModelIdentifier");

                    b.HasIndex("ProviderType");

                    b.ToTable("GenerationPromptSnapshots", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Images.GeneratedImageAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImageGenerationJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativeUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImageGenerationJobId");

                    b.ToTable("GeneratedImageAssets", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Images.ImageGenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Cfg")
                        .HasColumnType("REAL");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NegativePromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderJobId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Steps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("Status");

                    b.ToTable("ImageGenerationJobs", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Lorebooks.LoreEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LorebookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("LorebookId");

                    b.ToTable("LoreEntries", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Lorebooks.Lorebook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Lorebooks", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Memory.MemoryExtractionAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateNormalizedKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExistingMemoryContent")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExistingMemoryItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotFamily")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Kind");

                    b.HasIndex("SlotFamily");

                    b.ToTable("MemoryExtractionAuditEvents", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Memory.MemoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("ConflictsWithMemoryItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("DurableFact");

                    b.Property<string>("NormalizedKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposalReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Accepted");

                    b.Property<string>("SlotFamily")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<string>("SlotKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceExcerpt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ConflictsWithMemoryItemId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Kind");

                    b.HasIndex("ReviewStatus");

                    b.HasIndex("SlotFamily");

                    b.HasIndex("SlotKey");

                    b.HasIndex("CharacterId", "ConversationId", "Kind", "NormalizedKey");

                    b.HasIndex("CharacterId", "ConversationId", "Kind", "SlotFamily");

                    b.HasIndex("CharacterId", "ConversationId", "Kind", "SlotKey");

                    b.ToTable("MemoryItems", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Memory.SceneStateExtractionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateNormalizedKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedMemoryContent")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReplacedMemoryItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotFamily")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SlotFamily");

                    b.ToTable("SceneStateExtractionEvents", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Models.GenerationPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RepeatPenalty")
                        .HasColumnType("REAL");

                    b.Property<string>("StopSequencesText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<double>("TopP")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("GenerationPresets", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Models.ModelProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContextWindow")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelIdentifier")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("ModelProfiles", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Personas.UserPersona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalInstructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Traits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("UserPersonas", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Retrieval.RetrievalChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SourceType", "SourceEntityId")
                        .IsUnique();

                    b.ToTable("RetrievalChunks", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Settings.AppRuntimeDefaults", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultGenerationPresetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultModelProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultPersonaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppRuntimeDefaults", (string)null);
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Audio.SpeechClip", b =>
                {
                    b.HasOne("LocalChat.Domain.Entities.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalChat.Domain.Entities.Conversations.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalChat.Domain.Entities.Conversations.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Conversation");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Characters.Character", b =>
                {
                    b.HasOne("LocalChat.Domain.Entities.Models.GenerationPreset", "DefaultGenerationPreset")
                        .WithMany()
                        .HasForeignKey("DefaultGenerationPresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LocalChat.Domain.Entities.Models.ModelProfile", "DefaultModelProfile")
                        .WithMany()
                        .HasForeignKey("DefaultModelProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultGenerationPreset");

                    b.Navigation("DefaultModelProfile");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Characters.CharacterSampleDialogue", b =>
                {
                    b.HasOne("LocalChat.Domain.Entities.Characters.Character", "Character")
                        .WithMany("SampleDialogues")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Conversations.Conversation", b =>
                {
                    b.HasOne("LocalChat.Domain.Entities.Characters.Character", "Character")
                        .WithMany("Conversations")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalChat.Domain.Entities.Conversations.Conversation", "ParentConversation")
                        .WithMany()
                        .HasForeignKey("ParentConversationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LocalChat.Domain.Entities.Models.GenerationPreset", "RuntimeGenerationPresetOverride")
                        .WithMany()
                        .HasForeignKey("RuntimeGenerationPresetOverrideId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LocalChat.Domain.Entities.Models.ModelProfile", "RuntimeModelProfileOverride")
                        .WithMany()
                        .HasForeignKey("RuntimeModelProfileOverrideId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LocalChat.Domain.Entities.Personas.UserPersona", "UserPersona")
                        .WithMany("Conversations")
                        .HasForeignKey("UserPersonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Character");

                    b.Navigation("ParentConversation");

                    b.Navigation("RuntimeGenerationPresetOverride");

                    b.Navigation("RuntimeModelProfileOverride");

                    b.Navigation("UserPersona");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Conversations.Message", b =>
                {
                    b.HasOne("LocalChat.Domain.Entities.Conversations.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Conversations.MessageVariant", b =>
                {
                    b.HasOne("LocalChat.Domain.Entities.Conversations.Message", "Message")
                        .WithMany("Variants")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Conversations.SummaryCheckpoint", b =>
                {
                    b.HasOne("LocalChat.Domain.Entities.Conversations.Conversation", "Conversation")
                        .WithMany("SummaryCheckpoints")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Images.GeneratedImageAsset", b =>
                {
                    b.HasOne("LocalChat.Domain.Entities.Images.ImageGenerationJob", "ImageGenerationJob")
                        .WithMany("Assets")
                        .HasForeignKey("ImageGenerationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageGenerationJob");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Images.ImageGenerationJob", b =>
                {
                    b.HasOne("LocalChat.Domain.Entities.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalChat.Domain.Entities.Conversations.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Lorebooks.LoreEntry", b =>
                {
                    b.HasOne("LocalChat.Domain.Entities.Lorebooks.Lorebook", "Lorebook")
                        .WithMany("Entries")
                        .HasForeignKey("LorebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lorebook");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Memory.MemoryItem", b =>
                {
                    b.HasOne("LocalChat.Domain.Entities.Characters.Character", null)
                        .WithMany("Memories")
                        .HasForeignKey("CharacterId");

                    b.HasOne("LocalChat.Domain.Entities.Memory.MemoryItem", null)
                        .WithMany()
                        .HasForeignKey("ConflictsWithMemoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LocalChat.Domain.Entities.Conversations.Conversation", null)
                        .WithMany("Memories")
                        .HasForeignKey("ConversationId");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Characters.Character", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Memories");

                    b.Navigation("SampleDialogues");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Conversations.Conversation", b =>
                {
                    b.Navigation("Memories");

                    b.Navigation("Messages");

                    b.Navigation("SummaryCheckpoints");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Conversations.Message", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Images.ImageGenerationJob", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Lorebooks.Lorebook", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("LocalChat.Domain.Entities.Personas.UserPersona", b =>
                {
                    b.Navigation("Conversations");
                });
#pragma warning restore 612, 618
        }
    }
}
